name: non-prod-pipeline
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ACC_ID: "634758830486"
jobs:
  non-prod-pipeline-pipeline:
    runs-on: self-hosted
    steps:
    - name: Commit ID
      run: |
        APP_VERSION=$(echo "${{ inputs.version }}" | cut -c1-7)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "Using commit: $APP_VERSION"

    - name: Show Required Commit Checks Status
      env:
        GITHUB_TOKEN: ${{ github.token }}

      run: |

        COMMIT_SHA=${{ inputs.version }}

        echo "Checking commit: $COMMIT_SHA"


        CHECKS=$(curl -s \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/check-runs)


        echo "----- Required Checks Status -----"


        echo "$CHECKS" | jq -r '
          .check_runs[]
          | select(
              .name=="NPM Install" or
              .name=="APP VERSION" or
              .name=="DockerBuild" or
              .name=="ECR Push" or
              .name=="EKS Deploy"
            )
          | if .conclusion=="success"
            then "✅ \(.name) : PASSED"
            else "❌ \(.name) : FAILED (status=\(.status), conclusion=\(.conclusion))"
            end
        '


        FAILED=$(echo "$CHECKS" | jq '
          [
            .check_runs[]
            | select(
                (
                  .name=="NPM Install" or
                  .name=="APP VERSION" or
                  .name=="DockerBuild" or
                  .name=="ECR Push" or
                  .name=="EKS Deploy"
                )
                and
                (.conclusion != "success")
              )
          ] | length
        ')


        if [ "$FAILED" -gt 0 ]; then
          echo "❌ Required Commit Checks Failed"
          exit 1
        fi


        echo "✅ All Required Commit Checks Passed"
                    
                    